export const ActionTypes = {
  SET_DEVICES: "SET_DEVICES",
  SELECTED_DEVICE: "SELECTED_DEVICE",
  DELETE_DEVICE: "DELETE_DEVICE",
  SET_ERROR: "SET_ERROR",
  FILTER_DEVICES: "FILTER_DEVICES",
  CREATE_DEVICE: "CREATE_DEVICE",
};

export default ActionTypes;
