export const ActionTypes = {
  SET_DEVICES: "SET_DEVICES",
  SELECTED_DEVICE: "SELECTED_DEVICE",
  DELETE_DEVICE: "DELETE_DEVICE",
  SET_ERROR: "SET_ERROR",
  POST_REQUEST: "POST_REQUEST",
  CREATE_DEVICE: "CREATE_DEVICE",
  EDIT_DEVICE: "EDIT_DEVICE",
  FILTER_DEVICES: "FILTER_DEVICES",
  SET_FILTER: "SET_FILTER",
  SET_SORT: "SET_SORT"
};

export default ActionTypes;
